const mockUsers = [
  {
    id: '1',
    name: 'Anjali Nair',
    email: 'anjali.nair@example.com',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Thiruvananthapuram, Kerala',
    age: 28,
    gender: 'Female',
    status: 'active',
    isVerified: true,
    referralStatus: 'completed',
    walletBalance: 245.50,
    completedTasks: 23,
    joinDate: '2023-05-15',
    referrals: 3
  },
  {
    id: '2',
    name: 'Shad Muhammad',
    email: 'shad.muhammad@example.com',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Kozhikode, Kerala',
    age: 34,
    gender: 'Male',
    status: 'active',
    isVerified: true,
    referralStatus: 'pending',
    walletBalance: 189.75,
    completedTasks: 18,
    joinDate: '2023-07-22',
    referrals: 1
  },
  {
    id: '3',
    name: 'Reena Thomas',
    email: 'reena.thomas@example.com',
    avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Kottayam, Kerala',
    age: 26,
    gender: 'Female',
    status: 'inactive',
    isVerified: false,
    referralStatus: 'none',
    walletBalance: 67.25,
    completedTasks: 8,
    joinDate: '2023-09-10',
    referrals: 0
  },
  {
    id: '4',
    name: 'Vishnu Menon',
    email: 'vishnu.menon@example.com',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Palakkad, Kerala',
    age: 31,
    gender: 'Male',
    status: 'active',
    isVerified: true,
    referralStatus: 'completed',
    walletBalance: 312.80,
    completedTasks: 35,
    joinDate: '2023-03-28',
    referrals: 5
  },
  {
    id: '5',
    name: 'Jessy Mathew',
    email: 'jessy.mathew@example.com',
    avatar: 'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Ernakulam, Kerala',
    age: 29,
    gender: 'Female',
    status: 'banned',
    isVerified: false,
    referralStatus: 'none',
    walletBalance: 0.00,
    completedTasks: 2,
    joinDate: '2023-11-05',
    referrals: 0
  },
  {
    id: '6',
    name: 'Riyas Ali',
    email: 'riyas.ali@example.com',
    avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Malappuram, Kerala',
    age: 42,
    gender: 'Male',
    status: 'active',
    isVerified: true,
    referralStatus: 'completed',
    walletBalance: 478.90,
    completedTasks: 52,
    joinDate: '2023-01-12',
    referrals: 8
  },
  {
    id: '7',
    name: 'Bindu Raj',
    email: 'bindu.raj@example.com',
    avatar: 'https://images.pexels.com/photos/1239288/pexels-photo-1239288.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Thrissur, Kerala',
    age: 35,
    gender: 'Female',
    status: 'active',
    isVerified: true,
    referralStatus: 'pending',
    walletBalance: 156.40,
    completedTasks: 14,
    joinDate: '2023-06-30',
    referrals: 2
  },
  {
    id: '8',
    name: 'Noufal Rahman',
    email: 'noufal.rahman@example.com',
    avatar: 'https://images.pexels.com/photos/1212984/pexels-photo-1212984.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Kannur, Kerala',
    age: 38,
    gender: 'Male',
    status: 'inactive',
    isVerified: false,
    referralStatus: 'none',
    walletBalance: 23.75,
    completedTasks: 3,
    joinDate: '2023-10-18',
    referrals: 0
  },
  {
    id: '9',
    name: 'Meera Kurian',
    email: 'meera.kurian@example.com',
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Pathanamthitta, Kerala',
    age: 27,
    gender: 'Female',
    status: 'active',
    isVerified: true,
    referralStatus: 'completed',
    walletBalance: 298.60,
    completedTasks: 28,
    joinDate: '2023-04-08',
    referrals: 4
  },
  {
    id: '10',
    name: 'Akhil Dev',
    email: 'akhil.dev@example.com',
    avatar: 'https://images.pexels.com/photos/1542085/pexels-photo-1542085.jpeg?auto=compress&cs=tinysrgb&w=400',
    location: 'Alappuzha, Kerala',
    age: 32,
    gender: 'Male',
    status: 'active',
    isVerified: true,
    referralStatus: 'completed',
    walletBalance: 187.25,
    completedTasks: 19,
    joinDate: '2023-08-14',
    referrals: 2
  }
];

module.exports = { mockUsers };
